// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwMU4x7KnI95bCgPbaTr1MTbi2zNCXENs',
    appId: '1:50022293278:web:b9235ef53cb3422cddb30f',
    messagingSenderId: '50022293278',
    projectId: 'raagavaidya-51016',
    authDomain: 'raagavaidya-51016.firebaseapp.com',
    storageBucket: 'raagavaidya-51016.appspot.com',
    measurementId: 'G-LZJFE2CLRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZphru-xpjbi8ZwRD30VgY8XDYBjJ9W4',
    appId: '1:50022293278:android:d459e756f77e6155ddb30f',
    messagingSenderId: '50022293278',
    projectId: 'raagavaidya-51016',
    storageBucket: 'raagavaidya-51016.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApElKSr1wXm6jyNNvFHbkCbT2IKu7kXto',
    appId: '1:50022293278:ios:12142ea357ed08fbddb30f',
    messagingSenderId: '50022293278',
    projectId: 'raagavaidya-51016',
    storageBucket: 'raagavaidya-51016.appspot.com',
    iosBundleId: 'com.example.raagavaidya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApElKSr1wXm6jyNNvFHbkCbT2IKu7kXto',
    appId: '1:50022293278:ios:bfc651c4a543485fddb30f',
    messagingSenderId: '50022293278',
    projectId: 'raagavaidya-51016',
    storageBucket: 'raagavaidya-51016.appspot.com',
    iosBundleId: 'com.example.raagavaidya.RunnerTests',
  );
}
